### ISSUE TITLE
bugtrace after adding the monitoring_proxy to a host which is unknown to icinga2

### ISSUE THREAD

**Issue by hboetes** [theforeman/foreman_monitoring#15]
setting the monitoring_proxy for the icinga2 host itself works ok, but setting it for a host it does not know results in this error in the foreman-proxy logfile:

```
D, [2017-05-19T10:00:02.350345 ] DEBUG -- : close: 172.31.10.129:58176
D, [2017-05-19T10:00:02.424023 ] DEBUG -- : accept: 172.31.10.129:58178
D, [2017-05-19T10:00:02.426103 ] DEBUG -- : Rack::Handler::WEBrick is invoked.
D, [2017-05-19T10:00:02.428004 ] DEBUG -- : verifying remote client 172.31.10.129 against trusted_hosts ["george.foreman"]
E, [2017-05-19T10:00:02.452596 ] ERROR -- : Icinga server at icinga01.foreman returned an error: 'Error: Object does not exist.

	(0) libremote.so: void boost::throw_exception<boost::exception_detail::error_info_injector<std::invalid_argument> >(boost::exception_detail::error_info_injector<std::invalid_argument> const&) (+0x159) [0x7f7098751589]
	(1) libremote.so: void boost::exception_detail::throw_exception_<std::invalid_argument>(std::invalid_argument const&, char const*, char const*, int) (+0x67) [0x7f7098751667]
	(2) libremote.so: icinga::ConfigObjectTargetProvider::GetTargetByName(icinga::String const&, icinga::String const&) const (+0xb4) [0x7f70986f66e4]
	(3) libremote.so: icinga::FilterUtility::GetFilterTargets(icinga::QueryDescription const&, boost::intrusive_ptr<icinga::Dictionary> const&, boost::intrusive_ptr<icinga::ApiUser> const&) (+0x1ee) [0x7f70987189ce]
	(4) libremote.so: icinga::ObjectQueryHandler::HandleRequest(boost::intrusive_ptr<icinga::ApiUser> const&, icinga::HttpRequest&, icinga::HttpResponse&) (+0x603) [0x7f709871ea23]
	(5) libremote.so: icinga::HttpHandler::ProcessRequest(boost::intrusive_ptr<icinga::ApiUser> const&, icinga::HttpRequest&, icinga::HttpResponse&) (+0x5b4) [0x7f7098715924]
	(6) libremote.so: icinga::HttpServerConnection::ProcessMessageAsync(icinga::HttpRequest&) (+0x4a1) [0x7f7098716321]
	(7) libbase.so: icinga::WorkQueue::WorkerThreadProc() (+0x25f) [0x7f709994fc5f]
	(8) libboost_thread.so.1.58.0: <unknown function> (+0x115d5) [0x7f709a8dc5d5]
	(9) libpthread.so.0: <unknown function> (+0x76ba) [0x7f709a2336ba]
	(10) libc.so.6: clone (+0x6d) [0x7f709901282d]

'
D, [2017-05-19T10:00:02.452801 ] DEBUG -- : Icinga server at icinga01.foreman returned an error: 'Error: Object does not exist.

	(0) libremote.so: void boost::throw_exception<boost::exception_detail::error_info_injector<std::invalid_argument> >(boost::exception_detail::error_info_injector<std::invalid_argument> const&) (+0x159) [0x7f7098751589]
	(1) libremote.so: void boost::exception_detail::throw_exception_<std::invalid_argument>(std::invalid_argument const&, char const*, char const*, int) (+0x67) [0x7f7098751667]
	(2) libremote.so: icinga::ConfigObjectTargetProvider::GetTargetByName(icinga::String const&, icinga::String const&) const (+0xb4) [0x7f70986f66e4]
	(3) libremote.so: icinga::FilterUtility::GetFilterTargets(icinga::QueryDescription const&, boost::intrusive_ptr<icinga::Dictionary> const&, boost::intrusive_ptr<icinga::ApiUser> const&) (+0x1ee) [0x7f70987189ce]
	(4) libremote.so: icinga::ObjectQueryHandler::HandleRequest(boost::intrusive_ptr<icinga::ApiUser> const&, icinga::HttpRequest&, icinga::HttpResponse&) (+0x603) [0x7f709871ea23]
	(5) libremote.so: icinga::HttpHandler::ProcessRequest(boost::intrusive_ptr<icinga::ApiUser> const&, icinga::HttpRequest&, icinga::HttpResponse&) (+0x5b4) [0x7f7098715924]
	(6) libremote.so: icinga::HttpServerConnection::ProcessMessageAsync(icinga::HttpRequest&) (+0x4a1) [0x7f7098716321]
	(7) libbase.so: icinga::WorkQueue::WorkerThreadProc() (+0x25f) [0x7f709994fc5f]
	(8) libboost_thread.so.1.58.0: <unknown function> (+0x115d5) [0x7f709a8dc5d5]
	(9) libpthread.so.0: <unknown function> (+0x76ba) [0x7f709a2336ba]
	(10) libc.so.6: clone (+0x6d) [0x7f709901282d]
' (Proxy::Monitoring::Error)
/var/lib/gems/2.3.0/gems/smart_proxy_monitoring-0.1.0/lib/smart_proxy_monitoring_icinga2/monitoring_icinga2_main.rb:137:in `rescue in with_errorhandling'
/var/lib/gems/2.3.0/gems/smart_proxy_monitoring-0.1.0/lib/smart_proxy_monitoring_icinga2/monitoring_icinga2_main.rb:115:in `with_errorhandling'
/var/lib/gems/2.3.0/gems/smart_proxy_monitoring-0.1.0/lib/smart_proxy_monitoring_icinga2/monitoring_icinga2_main.rb:19:in `query_host'
/var/lib/gems/2.3.0/gems/smart_proxy_monitoring-0.1.0/lib/smart_proxy_monitoring/monitoring_api.rb:20:in `block in <class:Api>'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1610:in `call'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1610:in `block in compile!'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:975:in `block (3 levels) in route!'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:994:in `route_eval'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:975:in `block (2 levels) in route!'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1015:in `block in process_route'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1013:in `catch'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1013:in `process_route'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:973:in `block in route!'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:972:in `each'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:972:in `route!'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1085:in `block in dispatch!'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1067:in `block in invoke'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1067:in `catch'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1067:in `invoke'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1082:in `dispatch!'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:907:in `block in call!'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1067:in `block in invoke'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1067:in `catch'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1067:in `invoke'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:907:in `call!'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:895:in `call'
/usr/lib/ruby/vendor_ruby/rack/commonlogger.rb:33:in `call'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:219:in `call'
/usr/share/foreman-proxy/lib/proxy/log.rb:109:in `call'
/usr/share/foreman-proxy/lib/proxy/request_id_middleware.rb:9:in `call'
/usr/lib/ruby/vendor_ruby/rack/protection/xss_header.rb:18:in `call'
/usr/lib/ruby/vendor_ruby/rack/protection/path_traversal.rb:16:in `call'
/usr/lib/ruby/vendor_ruby/rack/protection/json_csrf.rb:18:in `call'
/usr/lib/ruby/vendor_ruby/rack/protection/base.rb:49:in `call'
/usr/lib/ruby/vendor_ruby/rack/protection/base.rb:49:in `call'
/usr/lib/ruby/vendor_ruby/rack/protection/frame_options.rb:31:in `call'
/usr/lib/ruby/vendor_ruby/rack/nulllogger.rb:9:in `call'
/usr/lib/ruby/vendor_ruby/rack/head.rb:13:in `call'
/usr/lib/ruby/vendor_ruby/sinatra/show_exceptions.rb:25:in `call'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:182:in `call'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:2013:in `call'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1487:in `block in call'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1787:in `synchronize'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1487:in `call'
/usr/lib/ruby/vendor_ruby/rack/urlmap.rb:66:in `block in call'
/usr/lib/ruby/vendor_ruby/rack/urlmap.rb:50:in `each'
/usr/lib/ruby/vendor_ruby/rack/urlmap.rb:50:in `call'
/usr/lib/ruby/vendor_ruby/rack/builder.rb:153:in `call'
/usr/lib/ruby/vendor_ruby/rack/handler/webrick.rb:88:in `service'
/usr/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
/usr/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
/usr/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
I, [2017-05-19T10:00:02.454095 ]  INFO -- : 172.31.10.129 - - [19/May/2017:10:00:02 +0200] "GET /monitoring/host/lars.foreman HTTP/1.1" 400 1585 0.0262

D, [2017-05-19T10:00:02.495094 ] DEBUG -- : close: 172.31.10.129:58178
I, [2017-05-19T10:00:06.300145 ]  INFO -- : Finished puppet class cache initialization
```

**Comment by timogoebel** [comment]
@dgoetz : Any idea, what might be causing this?

**Comment by hboetes** [comment]
For completeness sake: this is the same error in the icinga2 logfiles:
```
[2017-05-19 10:35:18 +0200] information/ApiListener: New client connection (no client certificate)
[2017-05-19 10:35:18 +0200] information/HttpServerConnection: Request: GET /v1/objects/hosts/james.foreman?attrs[]=vars&attrs[]=address&attrs[]=address6&attrs[]=templates (foreman)
[2017-05-19 10:35:18 +0200] critical/HttpServerConnection: Unhandled exception while processing Http request: Error: Object does not exist.

	(0) libremote.so: void boost::throw_exception<boost::exception_detail::error_info_injector<std::invalid_argument> >(boost::exception_detail::error_info_injector<std::invalid_argument> const&) (+0x159) [0x7fd277619589]
	(1) libremote.so: void boost::exception_detail::throw_exception_<std::invalid_argument>(std::invalid_argument const&, char const*, char const*, int) (+0x67) [0x7fd277619667]
	(2) libremote.so: icinga::ConfigObjectTargetProvider::GetTargetByName(icinga::String const&, icinga::String const&) const (+0xb4) [0x7fd2775be6e4]
	(3) libremote.so: icinga::FilterUtility::GetFilterTargets(icinga::QueryDescription const&, boost::intrusive_ptr<icinga::Dictionary> const&, boost::intrusive_ptr<icinga::ApiUser> const&) (+0x1ee) [0x7fd2775e09ce]
	(4) libremote.so: icinga::ObjectQueryHandler::HandleRequest(boost::intrusive_ptr<icinga::ApiUser> const&, icinga::HttpRequest&, icinga::HttpResponse&) (+0x603) [0x7fd2775e6a23]
	(5) libremote.so: icinga::HttpHandler::ProcessRequest(boost::intrusive_ptr<icinga::ApiUser> const&, icinga::HttpRequest&, icinga::HttpResponse&) (+0x5b4) [0x7fd2775dd924]
	(6) libremote.so: icinga::HttpServerConnection::ProcessMessageAsync(icinga::HttpRequest&) (+0x4a1) [0x7fd2775de321]
	(7) libbase.so: icinga::WorkQueue::WorkerThreadProc() (+0x25f) [0x7fd278817c5f]
	(8) libboost_thread.so.1.58.0: <unknown function> (+0x115d5) [0x7fd2797a45d5]
	(9) libpthread.so.0: <unknown function> (+0x76ba) [0x7fd2790fb6ba]
	(10) libc.so.6: clone (+0x6d) [0x7fd277eda82d]

```

**Comment by hboetes** [comment]
This error I found with google as well: https://github.com/Icinga/icinga2/issues/3898
And then it struck me, the ubuntu version of the icinga packages were installed. After deploying the packages from the icinga2 repo the problem was resolved.
