### ISSUE TITLE
Don't refresh all host statuses for every monitoring import

### ISSUE THREAD

**Issue by ananace** [theforeman/foreman_monitoring#52]
With https://github.com/theforeman/foreman_monitoring/blob/master/app/models/monitoring_result.rb#L37 every monitoring result import will cause the host to refresh every single status object attached to it, this can cause a lot of performance issues - among other things - if said status objects have to query external systems.  
Such as VMWare if using the wreckingball plugin.

**Comment by ananace** [comment]
Just FYI;

```
2018-06-19T09:41:05 7d9fc3d6 [app] [W] Failed to import monitoring result
 | Foreman::Exception: ERF42-1251 [Foreman::Exception]: Error has occurred while communicating with vc-liu-it (VMware): Got HTTP 503: Service unavailable
 | /usr/share/foreman/app/services/power_manager/virt.rb:15:in `rescue in initialize'
 | /usr/share/foreman/app/services/power_manager/virt.rb:7:in `initialize'
 | /usr/share/foreman/app/models/concerns/hostext/power_interface.rb:8:in `new'
 | /usr/share/foreman/app/models/concerns/hostext/power_interface.rb:8:in `power'
 | /usr/share/foreman/app/models/concerns/hostext/power_interface.rb:22:in `supports_power_and_running?'
 | /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/foreman_wreckingball-2.0.0/app/models/foreman_wreckingball/tools_status.rb:24:in `to_status'
 | /usr/share/foreman/app/models/host_status/status.rb:62:in `update_status'
 | /usr/share/foreman/app/models/host_status/status.rb:46:in `refresh'
 | /usr/share/foreman/app/models/host_status/status.rb:40:in `refresh!'
 | /usr/share/foreman/app/models/host/managed.rb:717:in `block in refresh_statuses'
 | /opt/rh/rh-ruby24/root/usr/share/ruby/set.rb:324:in `each_key'
 | /opt/rh/rh-ruby24/root/usr/share/ruby/set.rb:324:in `each'
 | /usr/share/foreman/app/models/host/managed.rb:715:in `refresh_statuses'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman_monitoring-1.0.1/app/models/monitoring_result.rb:37:in `import'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman_monitoring-1.0.1/app/controllers/api/v2/monitoring_results_controller.rb:20:in `create'
```

Not the tool status itself, but it does cause connections to VMWare when refreshing.
